---
- name: Install Docker, SonarQube, Git, and Configure User Access
  hosts: all
  become: yes

  vars:
    sonarqube_version: "latest"
    sonarqube_port: 9000
    git_user_name: "Your Name"  # Replace with your Git username
    git_user_email: "your-email@example.com"  # Replace with your Git email

  tasks:
    # Step 1: Update the package manager
    - name: Update apt packages
      apt:
        update_cache: yes

    # Step 2: Install Git
    - name: Install Git
      apt:
        name: git
        state: present

    # Step 3: Configure Git
    - name: Set Git user name
      command: git config --global user.name "{{ git_user_name }}"

    - name: Set Git user email
      command: git config --global user.email "{{ git_user_email }}"

    # Step 4: Install prerequisites for Docker
    - name: Install prerequisites for Docker
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    # Step 5: Add Docker's official GPG key and repository
    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present

    # Step 6: Install Docker
    - name: Install Docker
      apt:
        name: docker-ce
        state: present

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
        enabled: yes

    # Step 7: Add ubuntu and jenkins to the Docker group
    - name: Add ubuntu user to Docker group
      user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Add jenkins user to Docker group
      user:
        name: jenkins
        groups: docker
        append: yes

    # Step 8: Pull SonarQube Docker image
    - name: Pull SonarQube Docker image
      docker_image:
        name: sonarqube
        tag: "{{ sonarqube_version }}"
        source: pull

    # Step 9: Run SonarQube container
    - name: Start SonarQube container
      docker_container:
        name: sonarqube
        image: sonarqube:{{ sonarqube_version }}
        state: started
        ports:
          - "9000:{{ sonarqube_port }}"
        volumes:
          - /opt/sonarqube_data:/opt/sonarqube_data
